const WEBSITE_SERVICES = [
  { id:'w1', category:'Starter', name:'Portfolio / Personal Website',
    marketSetup:'₹18,750', marketMonthly:'₹1,249', setup:'₹15,000', monthly:'₹999',
    description:'Clean, fast, mobile-first personal or portfolio website.',
    tags:['Portfolio','Personal Branding','Mobile-First','Contact Form','Google Maps'],
    pages:'5–7 pages', deliveryDays:5,
    includes:['Custom design (mobile-first)','Contact form with WhatsApp CTA','Google Maps integration','Basic on-page SEO','SSL certificate + hosting setup'],
    maintenance:['Hosting & uptime monitoring','SSL renewal','Monthly content update (up to 2)','Bug fixes & technical support'],
    bestFor:['Freelancers','Photographers','Designers','Doctors','Lawyers'] },

  { id:'w2', category:'Starter', name:'Landing Page / Lead Gen Page',
    marketSetup:'₹12,500', marketMonthly:'₹799', setup:'₹9,999', monthly:'₹799',
    description:'Single high-converting landing page with lead form and WhatsApp CTA.',
    tags:['Lead Generation','Google Ads Ready','WhatsApp CTA','Fast Loading','A/B Ready'],
    pages:'1 page', deliveryDays:3,
    includes:['Single-page high-conversion design','Lead capture form + WhatsApp CTA','Google Ads / Meta Pixel ready','Mobile-first, Core Web Vitals optimized','Thank-you page setup'],
    maintenance:['Hosting & uptime monitoring','SSL certificate','Pixel / tracking tag updates','Minor copy or CTA changes (monthly)'],
    bestFor:['Startups','Coaches','Course Creators','Local Businesses','Event Promoters'] },

  { id:'w3', category:'Business', name:'Business / Service Website',
    marketSetup:'₹37,500', marketMonthly:'₹1,999', setup:'₹30,000', monthly:'₹1,599',
    description:'Full professional website for service businesses.',
    tags:['10–15 Pages','SEO Ready','WhatsApp Integration','Blog','Razorpay Ready'],
    pages:'10–15 pages', deliveryDays:10,
    includes:['Custom multi-page design','Blog setup with CMS','WhatsApp chat widget','On-page SEO (all pages)','Razorpay payment link integration'],
    maintenance:['Hosting & SSL','Monthly blog post upload (up to 4)','Content & image updates','Bug fixes & plugin updates','Monthly SEO health check'],
    bestFor:['Agencies','Consultants','Clinics','Coaching Centers','Local Service Businesses'] },

  { id:'w4', category:'Business', name:'E-Commerce Website (Basic)',
    marketSetup:'₹62,500', marketMonthly:'₹2,999', setup:'₹49,999', monthly:'₹2,499',
    description:'Full online store with product listings, cart, checkout, and order management.',
    tags:['Product Catalog','Razorpay/PayU','Cart & Checkout','Order Management','GST Invoice'],
    pages:'20–30 pages', deliveryDays:14,
    includes:['Product catalog (up to 100 products)','Cart, checkout & payment gateway (Razorpay/PayU)','Order management panel','GST invoice generation','Mobile-first responsive design'],
    maintenance:['Hosting & SSL','Payment gateway uptime monitoring','Product additions/edits (up to 20/month)','Order system bug fixes','Security & plugin updates'],
    bestFor:['D2C Brands','Retailers','Fashion Stores','Handicraft Sellers','Food & Beverage'] },

  { id:'w5', category:'Advanced', name:'E-Commerce Website (Advanced)',
    marketSetup:'₹1,25,000', marketMonthly:'₹4,999', setup:'₹99,999', monthly:'₹3,999',
    description:'Advanced store with AI recommendations, cart recovery, and analytics dashboard.',
    tags:['AI Recommendations','Cart Recovery','WhatsApp Bot','Loyalty Program','Analytics Dashboard'],
    pages:'50+ pages', deliveryDays:21,
    includes:['Everything in Basic E-Commerce','AI product recommendation engine','Abandoned cart recovery (WhatsApp + Email)','Customer loyalty program','Advanced analytics dashboard'],
    maintenance:['Hosting & SSL','AI model & API monitoring','Unlimited product updates','Cart recovery flow optimization','Monthly performance & revenue report'],
    bestFor:['Growing D2C Brands','Multi-Category Stores','Subscription Businesses','B2B Wholesalers'] },

  { id:'w6', category:'Business', name:'Restaurant / Hotel Website',
    marketSetup:'₹43,750', marketMonthly:'₹1,999', setup:'₹35,000', monthly:'₹1,599',
    description:'Hospitality website with menu, online booking, Google Maps, and WhatsApp ordering.',
    tags:['Menu Display','Table Booking','Room Booking','WhatsApp Order','Google Reviews'],
    pages:'8–12 pages', deliveryDays:7,
    includes:['Menu / room listing with photos','Online table / room booking system','Google Maps & Google Reviews integration','WhatsApp ordering button','Mobile-first design'],
    maintenance:['Hosting & SSL','Menu / room updates (up to 10/month)','Booking system uptime monitoring','Bug fixes & technical support'],
    bestFor:['Restaurants','Hotels','Resorts','Cafes','Cloud Kitchens'] },

  { id:'w7', category:'Business', name:'Educational / EdTech Website',
    marketSetup:'₹56,250', marketMonthly:'₹2,499', setup:'₹45,000', monthly:'₹1,999',
    description:'School, coaching institute, or online course website with student portal.',
    tags:['Course Listing','Batch Management','Fee Payment','Student Portal','Blog'],
    pages:'15–20 pages', deliveryDays:14,
    includes:['Course & batch listing pages','Fee payment gateway (Razorpay)','Student login portal','Blog & announcement section','Mobile app-ready design'],
    maintenance:['Hosting & SSL','Course / batch updates (unlimited)','Student portal uptime monitoring','Fee system checks','Monthly SEO update'],
    bestFor:['Coaching Institutes','Schools','Online Course Creators','EdTech Startups','Tutors'] },

  { id:'w8', category:'Advanced', name:'Real Estate Website',
    marketSetup:'₹75,000', marketMonthly:'₹2,999', setup:'₹60,000', monthly:'₹2,399',
    description:'Property listing website with search filters, map view, and CRM lead capture.',
    tags:['Property Listings','Search Filters','Map View','Virtual Tour','Lead Capture'],
    pages:'20–30 pages', deliveryDays:14,
    includes:['Property listing with advanced search filters','Map view (Google Maps integration)','Virtual tour embed support','WhatsApp inquiry bot','CRM lead capture & sync'],
    maintenance:['Hosting & SSL','Property listing updates (unlimited)','WhatsApp bot monitoring','CRM sync checks','Monthly lead quality report'],
    bestFor:['Real Estate Agents','Builders','Property Developers','Rental Agencies','Housing Platforms'] },

  { id:'w9', category:'Advanced', name:'SaaS / Startup Website',
    marketSetup:'₹1,00,000', marketMonthly:'₹3,999', setup:'₹80,000', monthly:'₹3,199',
    description:'Premium SaaS marketing site with animated hero, pricing table, and demo booking.',
    tags:['Animated Hero','Pricing Table','Demo Booking','Blog/Docs','Integrations Page'],
    pages:'15–25 pages', deliveryDays:14,
    includes:['Animated hero section','Pricing table with toggle (monthly/annual)','Demo booking flow','Blog / documentation section','Integrations showcase page'],
    maintenance:['Hosting & SSL','Pricing & copy updates','Blog post uploads (up to 4/month)','Demo booking flow monitoring','Monthly Core Web Vitals report'],
    bestFor:['SaaS Startups','Tech Companies','Product Companies','B2B Platforms','Fintech'] },

  { id:'w10', category:'Enterprise', name:'Corporate / Enterprise Website',
    marketSetup:'₹1,87,500', marketMonthly:'₹5,999', setup:'₹1,50,000', monthly:'₹4,799',
    description:'Large-scale corporate website with career portal, investor relations, and multilingual support.',
    tags:['Multi-Department','Career Portal','Investor Relations','News Center','Multilingual'],
    pages:'50+ pages', deliveryDays:30,
    includes:['Multi-department page architecture','Career portal with application system','Investor relations section','News & media center','Multilingual support (Hindi + English minimum)'],
    maintenance:['Hosting & SSL','Unlimited content updates','Career portal & form monitoring','Security audits (quarterly)','Priority technical support (48hr SLA)'],
    bestFor:['Corporations','Conglomerates','Government Bodies','NGOs','Large Enterprises'] },

  { id:'w11', category:'Advanced', name:'Marketplace / Directory Website',
    marketSetup:'₹2,50,000', marketMonthly:'₹7,999', setup:'₹2,00,000', monthly:'₹6,399',
    description:'Multi-vendor marketplace with listing management, reviews, and commission payments.',
    tags:['Multi-Vendor','Listing Management','Review System','Commission Payments','Search & Filter'],
    pages:'Custom', deliveryDays:30,
    includes:['Vendor / seller registration & panel','Listing creation & management','Review & rating system','Commission-based payment gateway','Advanced search & filter system'],
    maintenance:['Hosting & server uptime monitoring','SSL & security patches','Vendor support & onboarding assistance','Payment gateway reconciliation checks','Monthly platform health report'],
    bestFor:['Marketplace Startups','B2B Directories','Service Aggregators','Local Business Portals'] },

  { id:'w12', category:'Enterprise', name:'Custom Web Application',
    marketSetup:'Custom', marketMonthly:'Custom', setup:'Custom', monthly:'Custom',
    description:'Fully custom web app — dashboards, portals, SaaS platforms built to exact specs.',
    tags:['Custom Build','Dashboard','Portal','SaaS Platform','API Integration'],
    pages:'Custom', deliveryDays:'TBD',
    includes:['Full custom architecture & design','Any dashboard, portal, or platform','Third-party API integrations','Admin panel with role-based access','Deployment + handover documentation'],
    maintenance:['Hosting & infrastructure management','API & third-party monitoring','Bug fixes & feature updates','Security audits','Dedicated technical support'],
    bestFor:['Any Business Needing Custom Software','Enterprises','Government','Healthcare Networks'] }
];